app_contacts/urls.py
from django.urls import path

from app_contacts.views import DetailsView


app_name='contacts'

urlpatterns = [
    path('', DetailsView.as_view(), name='details'),
]

box/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_home.urls')),
    path('contacts/', include('app_contacts.urls')),
    path('documents/', include('app_documents.urls')),
    path('materials/', include('app_materials.urls')),
    path('news/', include('app_news.urls')),
    path('photo/', include('app_photo.urls')),
    path('schedule/', include('app_schedule.urls')),
    path('staff/', include('app_staff.urls')),
    path('video/', include('app_video.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_contacts/models.py
from django.core.validators import RegexValidator

from django.db import models


class Excursion(models.Model):
    """ Модель заявки на экскурсию """
    name = models.CharField(max_length=100, verbose_name='Имя')
    kid_name = models.CharField(max_length=100, verbose_name='Имя ребёнка')
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='Телефон', validators=[
        RegexValidator(
                regex=r'^79\d{9}$',
                message='Номер телефона должен начинаться с 79 и содержать 11 цифр, например: 79529999999',
            ),
        ]
    )
    email = models.EmailField(max_length=100, unique=True, verbose_name='E-mail')
    description = models.TextField(null=True, blank=True, verbose_name='Желаемая дата и время, вопросы')
    is_agree = models.BooleanField(default=False, blank=True, verbose_name='Согласие на обработку персональных данных')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    class Meta:
        verbose_name = "Заявка на экскурсию"
        verbose_name_plural = "Заявки на экскурсию"

    def __str__(self):
        return f'{self.name}: "{self.phone}" ({self.kid_name})'

app_contacts/forms.py
from django import forms
from django.core.validators import RegexValidator

from .models import Excursion


class ExcursionForm(forms.ModelForm):
    """ Форма заявки на экскурсию """
    name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'Input', 'placeholder': 'Имя', 'id': 'name'})
    )
    kid_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'Input', 'placeholder': 'Имя ребенка', 'id': 'name'})
    )
    phone = forms.CharField(
        max_length=11,
        required=True,
        label='Phone',
        widget=forms.TextInput(
            attrs={'class': 'Input', 'placeholder': '79520000000', 'id': 'phone'}
        ),
        validators=[
            RegexValidator(
                regex=r'^79\d{9}$',
                message='Номер телефона должен начинаться с 79 и содержать 11 цифр, например: 79529999999',
            ),
        ]
    )
    email = forms.EmailField(
        required=True,
        label='Email',
        widget=forms.EmailInput(
            attrs={'class': 'Input', 'placeholder': 'my@gmail.com', 'id': 'email'}
        )
    )
    description = forms.CharField(
        max_length=9999,
        required=False,
        widget=forms.Textarea(attrs={'class': 'Textarea', 'placeholder': 'Желаемая дата и время, вопросы', 'id': 'description'})
    )

    class Meta:
        model = Excursion
        fields = ['name', 'kid_name', 'phone', 'email', 'description', 'is_agree']
        widgets = {
            'description': forms.Textarea(attrs={
                'placeholder': 'Your comment...', 'rows': 4, 'min-length': 20, 'required': True, 'class': 'Textarea'
            }),
        }

app_contacts/views.py
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponse, HttpRequest

from .forms import ExcursionForm


class DetailsView(View):
    """ EndPoint показа страницы контакта """
    def get(self, request: HttpRequest) -> HttpResponse:
        form = ExcursionForm()
        ctx = {
            'form': form,
        }
        return render(request, 'contacts/details.html', ctx)

    """ EndPoint добавления заявки """
    def post(self, request: HttpRequest) -> HttpResponse:
        form = ExcursionForm(request.POST)

        if form.is_valid():
            form.save()
            print('valid')
            messages.success(request, 'Заявка успешно добавлена')
        else:
            messages.error(request, 'Заявка не добавлена')
            print(form.errors)

        return render(request, 'contacts/details.html', {'form': form})

app_contacts/templates/contacts/details.html
{% extends 'base/index.html' %}
{% load static %}

{% block title %}Контакты{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static '/pages/contacts/css/styles.css' %}">
{% endblock %}

{% block body %}
<h1>Contacts</h1>

    <div class="form-block">
        <form action="{% url 'contacts:details' %}" method="post" class="form">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                {{ form.name }}
                {% if form.name.errors %}<div class="error">{{ form.name.errors }}</div>{% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.kid_name.id_for_label }}">{{ form.kid_name.label }}</label>
                {{ form.kid_name }}
                {% if form.kid_name.errors %}<div class="error">{{ form.kid_name.errors }}</div>{% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                {{ form.phone }}
                {% if form.phone.errors %}<div class="error">{{ form.phone.errors }}</div>{% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                {{ form.email }}
                {% if form.email.errors %}<div class="error">{{ form.email.errors }}</div>{% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                {{ form.description }}
                {% if form.description.errors %}<div class="error">{{ form.description.errors }}</div>{% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.is_agree.id_for_label }}">{{ form.is_agree.label }}</label>
                {{ form.is_agree }}
                {% if form.is_agree.errors %}<div class="error">{{ form.is_agree.errors }}</div>{% endif %}
            </div>

            <button type="submit" class="button">
                <i class="fa-solid fa-message"></i>
                <span>Отправить заявку</span>
            </button>
        </form>
    </div>

{% endblock %}