app_home/urls.py
from django.urls import path

from app_home.views import DetailsView


app_name='home'

urlpatterns = [
    path('', DetailsView.as_view(), name='details'),
]

app_news/urls.py
from django.urls import path

from app_news.views import DetailsView


app_name='news'

urlpatterns = [
    path('', DetailsView.as_view(), name='details'),
]

app_photo/urls.py
from django.urls import path

from app_photo.views import DetailsView


app_name='photo'

urlpatterns = [
    path('', DetailsView.as_view(), name='details'),
]

app_staff/urls.py
from django.urls import path

from app_staff.views import DetailsView


app_name='staff'

urlpatterns = [
    path('', DetailsView.as_view(), name='details'),
]

box/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_home.urls')),
    path('contacts/', include('app_contacts.urls')),
    path('documents/', include('app_documents.urls')),
    path('materials/', include('app_materials.urls')),
    path('news/', include('app_news.urls')),
    path('photo/', include('app_photo.urls')),
    path('schedule/', include('app_schedule.urls')),
    path('staff/', include('app_staff.urls')),
    path('video/', include('app_video.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/parts/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col col-lg-3 d-none d-lg-block">
                <div class="logo">
                    <a href="{% url 'home:details' %}" class="logo__link">
                        <img src="{{ site_settings.logo.url }}" alt="logo" class="logo__img">
                    </a>
                </div>
                {% include 'parts/social.html' with bg='#FFEDB7' text='#9EB378' size=40 %}
            </div>
            <div class="col col-lg-5 d-none d-lg-flex align-items-center">
                <nav class="nav">
                    <ul class="nav__list">
                        <li class="nav__item">
                            <a href="#" class="nav__link text-row">О нас</a>
                        </li>
                        <li class="nav__item">
                            <a href="#" class="nav__link text-row">Образование</a>
                        </li>
                        <li class="nav__item">
                            <a href="#" class="nav__link text-row">Родителям</a>
                        </li>
                        <li class="nav__item">
                            <a href="#" class="nav__link text-row">Галерея</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col col-lg-4">
                <div class="text-row mb-1">г. Москва, ул. Московcкая, д. 32б</div>
                <div class="text-row mb-1">Пн-Пт с 8:00 до 20:00</div>
                <div class="text-row mb-1">+7(999)999 99 99</div>
                <div class="text-row mb-2">MoskowDS@gmail.ru</div>
                <div class="d-lg-none">
                    {% include 'parts/social.html' %}
                </div>
            </div>
        </div>
    </div>
</footer>

templates/parts/header.html
{% load static %}
<header class="header">
    <div class="container">
        <div class="row align-items-center">
            <div class="col col-lg-1 logo">
                <a href="{% url 'home:details' %}" class="logo__link">
                    <img src="{{ site_settings.logo.url }}" alt="logo" class="logo__img">
                </a>
            </div>
            <div class="col nav d-flex d-lg-none justify-content-end align-content-center">
                <button class="nav__btn" id="mobile-menu-btn">
                    <span class="burger" id="burger">
                        <span class="burger__inner"></span>
                    </span>
                </button>
            </div>
            <nav class="col-lg-11 d-none d-lg-flex justify-content-end header__nav">
                <ul class="header__nav-list d-flex justify-content-between">
                    <li class="header__nav-item"><a href="{% url 'home:details' %}" class="header__nav-link text-row">Главная</a></li>
                    <li class="header__nav-item"><a href="{% url 'documents:details' %}" class="header__nav-link text-row">Документы</a></li>
                    <li class="header__nav-item"><a href="{% url 'materials:details' %}" class="header__nav-link text-row">Материалы</a></li>
                    <li class="header__nav-item"><a href="{% url 'news:details' %}" class="header__nav-link text-row">Новости</a></li>
                    <li class="header__nav-item"><a href="{% url 'photo:details' %}" class="header__nav-link text-row">Фото</a></li>
                    <li class="header__nav-item"><a href="{% url 'video:details' %}" class="header__nav-link text-row">Видео</a></li>
                    <li class="header__nav-item"><a href="{% url 'schedule:details' %}" class="header__nav-link text-row">Расписание</a></li>
                    <li class="header__nav-item"><a href="{% url 'staff:details' %}" class="header__nav-link text-row">Коллектив</a></li>
                    <li class="header__nav-item"><a href="{% url 'contacts:details' %}" class="header__nav-link text-row">Контакты</a></li>
                </ul>
            </nav>
        </div>
    </div>

    <div class="drawer" id="drawer">
        <nav class="drawer__nav">
            <ul class="drawer__list">
                <li class="header__nav-item"><a href="{% url 'home:details' %}" class="header__nav-link text-row">Главная</a></li>
                <li class="header__nav-item"><a href="{% url 'documents:details' %}" class="header__nav-link text-row">Документы</a></li>
                <li class="header__nav-item"><a href="{% url 'materials:details' %}" class="header__nav-link text-row">Материалы</a></li>
                <li class="header__nav-item"><a href="{% url 'news:details' %}" class="header__nav-link text-row">Новости</a></li>
                <li class="header__nav-item"><a href="{% url 'photo:details' %}" class="header__nav-link text-row">Фото</a></li>
                <li class="header__nav-item"><a href="{% url 'video:details' %}" class="header__nav-link text-row">Видео</a></li>
                <li class="header__nav-item"><a href="{% url 'schedule:details' %}" class="header__nav-link text-row">Расписание</a></li>
                <li class="header__nav-item"><a href="{% url 'staff:details' %}" class="header__nav-link text-row">Коллектив</a></li>
                <li class="header__nav-item"><a href="{% url 'contacts:details' %}" class="header__nav-link text-row">Контакты</a></li>
            </ul>
        </nav>
    </div>
</header>

templates/parts/social.html
<div class="social">
    <ul class="social__list">
        <li class="social__item">
            <a href="#" class="social__link" style="font-size: 30px;">
                <svg class='social__icon' style="max-height: 30px;">
                  <use href='#icon-vk'></use>
                </svg>
            </a>
        </li>
        <li class="social__item">
            <a href="#" class="social__link" style="font-size: 30px;">
                <svg class='social__icon' style="max-height: 30px;">
                  <use href='#icon-viber'></use>
                </svg>
            </a>
        </li>
        <li class="social__item">
            <a href="#" class="social__link" style="font-size: 30px;">
                <svg class='social__icon' style="max-height: 30px;">
                  <use href='#icon-tg'></use>
                </svg>
            </a>
        </li>
    </ul>
</div>
{{ site_settings.icons|safe }}